
import ExifParser from "exif-parser";
import sharp from "sharp";
import Tesseract from "tesseract.js";
import axios from "axios";

// ==================== DEEPFAKE KILL SWITCHES ====================
const DEEPFAKE_KEYWORDS = {
  photoshop: ["photoshop", "adobe photoshop", "ps", "psb"],
  stable_diffusion: ["stable diffusion", "stablediffusion", "sd"],
  midjourney: ["midjourney", "mj"],
  dalle: ["dall-e", "dalle", "openai"],
  gemini: ["gemini", "bard", "google.ai", "google ai", "imagen"],
  firefly: ["adobe firefly", "firefly"],
  leonardo: ["leonardo", "leonardo.ai"],
  canva: ["canva", "canva.com"],
  ai_generated: ["ai generated", "generated by ai", "artificial intelligence"],
};

const WATERMARK_KEYWORDS = [
  "watermark",
  "stock",
  "getty",
  "shutterstock",
  "istockphoto",
  "adobe",
  "istock",
  "alamy",
  "depositphotos",
  "123rf",
  "dreamstime",
  "fotolia",
  "pond5",
  "bigstock",
];

/**
 * ==================== POCKET DETECTOR ====================
 */
const checkIfPocket = async (imageBuffer) => {
  try {
    console.log("\n📱 Pocket Detection...");

    const data = await sharp(imageBuffer)
      .resize(100, 100) // Speed up analysis
      .raw()
      .toBuffer({ resolveWithObject: true });

    const pixels = data.data;
    let totalBrightness = 0;
    let darkPixels = 0;
    const totalPixelCount = pixels.length / 4; // RGBA

    for (let i = 0; i < pixels.length; i += 4) {
      const r = pixels[i];
      const g = pixels[i + 1];
      const b = pixels[i + 2];
      const brightness = 0.299 * r + 0.587 * g + 0.114 * b;
      totalBrightness += brightness;

      if (brightness < 30) darkPixels++; // Very dark pixels
    }

    const avgBrightness = totalBrightness / totalPixelCount / 255;
    const darkPixelRatio = darkPixels / totalPixelCount;
    const isPocket = avgBrightness < 0.15 && darkPixelRatio > 0.8;

    console.log(`   Average brightness: ${(avgBrightness * 100).toFixed(1)}%`);
    console.log(`   Dark pixels: ${(darkPixelRatio * 100).toFixed(1)}%`);
    console.log(`   Is pocket: ${isPocket}`);

    return {
      isPocket,
      avgBrightness,
      darkPixelRatio,
      brightnessPercent: (avgBrightness * 100).toFixed(1),
    };
  } catch (err) {
    console.log("⚠️ Pocket detection failed:", err.message);
    return {
      isPocket: false,
      avgBrightness: 0.5,
      darkPixelRatio: 0,
      brightnessPercent: "50",
    };
  }
};

/**
 * ==================== EXIF METADATA CHECK ====================
 */
const analyzeExifData = (imageBuffer) => {
  try {
    console.log("\n📋 EXIF Metadata Analysis...");

    const parser = ExifParser.create(imageBuffer);
    const result = parser.parse();
    const tags = result.tags || {};

    const metadata = {
      make: String(tags.Make || "Unknown"),
      model: String(tags.Model || "Unknown"),
      software: String(tags.Software || ""),
      dateTime: tags.DateTime,
      gpsLatitude: tags.GPSLatitude,
      gpsLongitude: tags.GPSLongitude,
      orientation: tags.Orientation,
      xResolution: tags.XResolution,
      yResolution: tags.YResolution,
    };

    // Check for AI generation signatures in metadata
    const suspiciousText =
      `${metadata.software} ${metadata.model} ${metadata.make}`.toLowerCase();
    let aiDetected = false;
    let aiSource = null;

    for (const [tool, keywords] of Object.entries(DEEPFAKE_KEYWORDS)) {
      for (const keyword of keywords) {
        if (suspiciousText.includes(keyword.toLowerCase())) {
          aiDetected = true;
          aiSource = tool;
          console.log(`   🚨 AI signature detected: "${keyword}" in ${tool}`);
          break;
        }
      }
      if (aiDetected) break;
    }

    console.log(`   Make: ${metadata.make}`);
    console.log(`   Model: ${metadata.model}`);
    console.log(`   Software: ${metadata.software || "(none)"}`);
    console.log(`   AI Detected: ${aiDetected}`);

    return {
      metadata,
      aiDetected,
      aiSource,
      hasValidGPS: !!(metadata.gpsLatitude && metadata.gpsLongitude),
      hasTimestamp: !!metadata.dateTime,
    };
  } catch (err) {
    console.log("⚠️ EXIF analysis failed:", err.message);
    return {
      metadata: {},
      aiDetected: false,
      aiSource: null,
      hasValidGPS: false,
      hasTimestamp: false,
    };
  }
};

/**
 * ==================== WATERMARK/OCR DETECTION ====================
 */
const detectWatermarksAndText = async (imageBuffer) => {
  try {
    console.log("\n💧 Watermark & Text Detection...");

    // Enhance image for better OCR
    const enhancedBuffer = await sharp(imageBuffer)
      .resize(800, 600, { fit: "inside", withoutEnlargement: true })
      .sharpen()
      .normalize()
      .png()
      .toBuffer();

    const worker = await Tesseract.createWorker("eng");
    const result = await worker.recognize(enhancedBuffer);
    const detectedText = result.data.text.toLowerCase();
    await worker.terminate();

    const confidence = result.data.confidence;
    console.log(`   OCR Confidence: ${confidence.toFixed(1)}%`);
    console.log(`   Text found: ${detectedText.length > 0 ? "Yes" : "No"}`);

    if (detectedText.length > 10) {
      console.log(`   Sample text: "${detectedText.substring(0, 100)}..."`);
    }

    // Check for watermarks and AI signatures
    const foundWatermarks = [];
    const aiSignatures = [];

    for (const watermark of WATERMARK_KEYWORDS) {
      if (detectedText.includes(watermark)) {
        foundWatermarks.push(watermark);
      }
    }

    for (const [tool, keywords] of Object.entries(DEEPFAKE_KEYWORDS)) {
      for (const keyword of keywords) {
        if (detectedText.includes(keyword)) {
          aiSignatures.push(keyword);
        }
      }
    }

    console.log(`   Watermarks found: ${foundWatermarks.length}`);
    console.log(`   AI signatures found: ${aiSignatures.length}`);

    return {
      detectedText,
      confidence,
      foundWatermarks,
      aiSignatures,
      hasText: detectedText.length > 10,
      suspiciousText: foundWatermarks.length > 0 || aiSignatures.length > 0,
    };
  } catch (err) {
    console.log("⚠️ Text detection failed:", err.message);
    return {
      detectedText: "",
      confidence: 0,
      foundWatermarks: [],
      aiSignatures: [],
      hasText: false,
      suspiciousText: false,
    };
  }
};

/**
 * ==================== AI DETECTION WITH GEMMA3:4B ====================
 */
const detectAIWithGemma = async (imageBase64) => {
  try {
    console.log("\n🔬 AI Detection (Gemma3:4b)...");

    const cleanBase64 = imageBase64.replace(
      /^data:image\/[a-zA-Z]+;base64,/,
      "",
    );

    const forensicPrompt = `
You are an expert forensic analyst. Analyze this image to determine if it's AI-generated or a real photograph.

LOOK FOR AI GENERATION SIGNS:
- Hands: Wrong number of fingers, merged fingers, unnatural hand positions
- Faces: Asymmetrical features, uncanny valley effect, plastic-looking skin
- Text: Gibberish, squiggly lines, nonsensical words or letters
- Physics: Impossible shadows, floating objects, inconsistent lighting
- Textures: Overly smooth skin, repetitive patterns, lack of natural imperfections
- Eyes: Mismatched sizes, strange pupils, unnatural gaze direction
- Background: Blurred edges, objects merging into each other

LOOK FOR REAL PHOTO SIGNS:
- Natural imperfections: skin pores, wrinkles, blemishes
- Consistent physics: proper shadows, realistic lighting
- Natural textures: fabric weave, surface roughness, wear patterns
- Clear readable text: proper fonts, correct spelling
- Natural poses and expressions
- Camera artifacts: motion blur, depth of field, noise

Be conservative - only mark as AI-generated if you see CLEAR artificial signs.

Respond with ONLY this JSON:
{
  "is_ai_generated": false,
  "confidence": 25,
  "ai_indicators": ["list of AI signs you found"],
  "real_indicators": ["list of real photo signs you found"],
  "reasoning": "Brief explanation of your decision"
}
`;

    const response = await axios.post(
      "http://localhost:11434/api/generate",
      {
        model: "gemma3:4b",
        prompt: forensicPrompt,
        images: [cleanBase64],
        stream: false,
        format: "json",
        options: {
          temperature: 0.1, // Very low for consistent results
          top_p: 0.9,
        },
      },
      { timeout: 90000 },
    );

    let analysis;
    try {
      analysis = JSON.parse(response.data.response);
    } catch (parseError) {
      const responseText = response.data.response;
      const jsonMatch = responseText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        analysis = JSON.parse(jsonMatch[0]);
      } else {
        analysis = {
          is_ai_generated: false,
          confidence: 10,
          ai_indicators: [],
          real_indicators: ["Analysis failed - assuming real"],
          reasoning: "Could not parse AI analysis response",
        };
      }
    }

    console.log(`   AI Generated: ${analysis.is_ai_generated}`);
    console.log(`   Confidence: ${analysis.confidence || 0}%`);
    console.log(`   AI Indicators: ${(analysis.ai_indicators || []).length}`);
    console.log(
      `   Real Indicators: ${(analysis.real_indicators || []).length}`,
    );

    return {
      isAI: analysis.is_ai_generated === true,
      confidence: Math.max(0, Math.min(100, analysis.confidence || 0)),
      aiIndicators: analysis.ai_indicators || [],
      realIndicators: analysis.real_indicators || [],
      reasoning: analysis.reasoning || "Analysis complete",
    };
  } catch (err) {
    console.error("❌ Gemma AI detection error:", err.message);
    return {
      isAI: false,
      confidence: 0,
      aiIndicators: [],
      realIndicators: ["Analysis failed - assuming real"],
      reasoning: `Error: ${err.message}`,
    };
  }
};

/**
 * ==================== MAIN FORENSICS FUNCTION ====================
 */
export const analyzeForensics = async (
  imageBuffer,
  mode = "UPLOAD",
  imageBase64 = null,
) => {
  try {
    console.log("\n\n" + "=".repeat(70));
    console.log("🔍 FORENSICS ANALYSIS PIPELINE");
    console.log(`📱 Mode: ${mode}`);
    console.log("=".repeat(70));

    // Special handling for SHAKE_HYBRID mode
    if (mode === "SHAKE_HYBRID") {
      console.log("✅ SHAKE_HYBRID mode - Trusted live capture");
      const pocketCheck = await checkIfPocket(imageBuffer);

      return {
        realismFactor: 1.0,
        isFake: false,
        confidenceScore: 5, // Very low fake confidence
        isPocket: pocketCheck.isPocket,
        verdict: pocketCheck.isPocket
          ? "📱 Live capture (pocket mode - audio priority)"
          : "📱 Live capture verified",
        deepfakeIndicators: [],
        analysis: {
          mode: "SHAKE_HYBRID",
          trusted: true,
          pocketAnalysis: pocketCheck,
        },
      };
    }

    // Phase 1: EXIF Metadata Analysis
    const exifAnalysis = analyzeExifData(imageBuffer);

    // If clear AI signature in metadata, flag but don't block
    if (exifAnalysis.aiDetected) {
      console.log("🚨 AI signature found in EXIF metadata");
      return {
        realismFactor: 0.1, // Very low but not zero
        isFake: true,
        confidenceScore: 95,
        isPocket: false,
        verdict: `⚠️ AI signature detected: ${exifAnalysis.aiSource}`,
        deepfakeIndicators: [`EXIF: ${exifAnalysis.aiSource}`],
        analysis: {
          method: "EXIF_DETECTION",
          exifData: exifAnalysis,
          aiSource: exifAnalysis.aiSource,
        },
      };
    }

    // Phase 2: Basic image quality checks
    const pocketCheck = await checkIfPocket(imageBuffer);

    // Phase 3: Watermark and text detection
    const textAnalysis = await detectWatermarksAndText(imageBuffer);

    // If AI signatures found in text, flag but don't block
    if (textAnalysis.suspiciousText && textAnalysis.aiSignatures.length > 0) {
      console.log("🚨 AI signatures found in image text");
      return {
        realismFactor: 0.2,
        isFake: true,
        confidenceScore: 90,
        isPocket: pocketCheck.isPocket,
        verdict: `⚠️ AI signatures in text: ${textAnalysis.aiSignatures.join(", ")}`,
        deepfakeIndicators: textAnalysis.aiSignatures,
        analysis: {
          method: "TEXT_DETECTION",
          textAnalysis: textAnalysis,
          pocketAnalysis: pocketCheck,
        },
      };
    }

    // Phase 4: Advanced AI detection with Gemma
    let aiAnalysis = { isAI: false, confidence: 0 };
    if (imageBase64) {
      aiAnalysis = await detectAIWithGemma(imageBase64);
    }

    // Determine final verdict
    const isLikelyFake = aiAnalysis.isAI && aiAnalysis.confidence > 60;

    let verdict, realismFactor, confidenceScore;

    if (isLikelyFake) {
      verdict = `⚠️ Suspected AI-generated (${aiAnalysis.confidence}% confidence)`;
      realismFactor = Math.max(0.1, 1.0 - aiAnalysis.confidence / 100); // Scale from 0.1 to 0.4
      confidenceScore = aiAnalysis.confidence;
      console.log(
        "🚨 Image flagged as likely AI-generated (low trust score applied)",
      );
    } else {
      verdict = "✅ Appears to be real photograph";
      realismFactor = 1.0;
      confidenceScore = Math.max(0, 100 - aiAnalysis.confidence);
      console.log("✅ Image appears authentic");
    }

    return {
      realismFactor: realismFactor,
      isFake: isLikelyFake,
      confidenceScore: aiAnalysis.confidence || 0,
      isPocket: pocketCheck.isPocket,
      verdict: verdict,
      deepfakeIndicators: isLikelyFake ? aiAnalysis.aiIndicators : [],
      analysis: {
        method: "COMPREHENSIVE",
        exifData: exifAnalysis.metadata,
        pocketAnalysis: pocketCheck,
        textAnalysis: {
          hasText: textAnalysis.hasText,
          confidence: textAnalysis.confidence,
          watermarksFound: textAnalysis.foundWatermarks.length,
        },
        aiAnalysis: {
          model: "gemma3:4b",
          confidence: aiAnalysis.confidence,
          aiIndicatorCount: aiAnalysis.aiIndicators.length,
          realIndicatorCount: aiAnalysis.realIndicators.length,
          reasoning: aiAnalysis.reasoning,
        },
      },
    };
  } catch (err) {
    console.error("❌ Forensics pipeline error:", err.message);

    // Fail-safe: Accept image with warning
    return {
      realismFactor: 0.8, // Slightly reduced due to analysis failure
      isFake: false,
      confidenceScore: 10,
      isPocket: false,
      verdict: "⚠️ Analysis failed - accepted with caution",
      deepfakeIndicators: ["Analysis error"],
      analysis: {
        method: "FAILED",
        error: err.message,
        failsafe: true,
      },
    };
  }
};

export default {
  analyzeForensics,
  checkIfPocket,
  analyzeExifData,
  detectWatermarksAndText,
  detectAIWithGemma,
};
